import type {
  Deal,
  FollowUp,
  FollowUpType,
  Lead,
  LeadSource,
  TeamMember,
} from "./types";

/**
 * DEMO DATA ONLY — Step 1.
 * Dates are generated relative to "now" so the demo always looks live.
 * In Step 2 this module is replaced by real sources:
 *   - Facebook Lead Ads (Graph API)  -> leads
 *   - Hotel Mate PMS API             -> bookings / customers
 */

const now = new Date();

function daysAgo(days: number, hour = 10, minute = 30): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function daysAhead(days: number, hour = 10, minute = 0): string {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const HOTLINE = "+94 78 860 7143";
export const HOTLINE_TEL = "+94788607143";

export const team: TeamMember[] = [
  { name: "Ashan Silva", role: "Sales Manager" },
  { name: "Nimmi Perera", role: "Sales Executive" },
  { name: "Ravindu Fernando", role: "Sales Executive" },
];

export const leads: Lead[] = [
  {
    id: "L-1042",
    name: "Nuwan Jayasuriya",
    hotel: "Serendipity Beach Resort",
    location: "Negombo",
    phone: "+94 77 555 2210",
    email: "nuwan@serendipitybeach.lk",
    source: "facebook",
    campaign: "HM Lead Gen — September",
    interest: "Full PMS + Channel Manager",
    budgetLKR: 185000,
    status: "new",
    assignedTo: "Ashan Silva",
    createdAt: daysAgo(0, 8, 42),
    note: "42 rooms, currently using spreadsheets. Wants OTA sync urgently.",
  },
  {
    id: "L-1041",
    name: "Dilini Fernando",
    hotel: "Cinnamon Grove Boutique",
    location: "Colombo 07",
    phone: "+94 76 442 8871",
    email: "dilini@cinnamongrove.lk",
    source: "instagram",
    campaign: "IG Reels — HotelMate Demo",
    interest: "Direct Booking Engine",
    budgetLKR: 95000,
    status: "contacted",
    assignedTo: "Nimmi Perera",
    createdAt: daysAgo(1, 14, 15),
    note: "Replied to DM. Asked for pricing sheet.",
  },
  {
    id: "L-1040",
    name: "Kasun Bandara",
    hotel: "Hilltop Eco Retreat",
    location: "Kandy",
    phone: "+94 71 903 5544",
    source: "facebook",
    campaign: "HM Lead Gen — September",
    interest: "PMS + POS bundle",
    budgetLKR: 140000,
    status: "qualified",
    assignedTo: "Ashan Silva",
    createdAt: daysAgo(2, 11, 5),
    note: "Demo scheduled. Owner + 2 managers joining.",
  },
  {
    id: "L-1039",
    name: "Tharushi Wickramasinghe",
    hotel: "Sunset Bay Villas",
    location: "Mirissa",
    phone: "+94 70 221 7788",
    email: "hello@sunsetbayvillas.lk",
    source: "whatsapp",
    campaign: "WhatsApp Business Inquiry",
    interest: "Channel Manager (Booking + Agoda)",
    budgetLKR: 75000,
    status: "proposal",
    assignedTo: "Ravindu Fernando",
    createdAt: daysAgo(3, 16, 40),
    note: "Proposal v2 sent. Waiting for owner approval.",
  },
  {
    id: "L-1038",
    name: "Mohamed Rizwan",
    hotel: "Grand Palm Hotel",
    location: "Colombo 03",
    phone: "+94 77 810 3345",
    email: "rizwan@grandpalm.lk",
    source: "website",
    campaign: "hotelmate.co.uk — Get Started form",
    interest: "Enterprise PMS (3 properties)",
    budgetLKR: 420000,
    status: "won",
    assignedTo: "Ashan Silva",
    createdAt: daysAgo(6, 9, 20),
    note: "Signed 12-month contract. Onboarding next week.",
  },
  {
    id: "L-1037",
    name: "Anusha Perera",
    hotel: "Lotus Garden Hotel",
    location: "Nuwara Eliya",
    phone: "+94 75 667 1123",
    source: "facebook",
    campaign: "HM Lead Gen — September",
    interest: "PMS Starter",
    budgetLKR: 45000,
    status: "new",
    assignedTo: "Nimmi Perera",
    createdAt: daysAgo(0, 7, 55),
  },
  {
    id: "L-1036",
    name: "Ruwan Silva",
    hotel: "Blue Horizon Beach Hotel",
    location: "Unawatuna",
    phone: "+94 72 334 9087",
    email: "ruwan@bluehorizon.lk",
    source: "facebook",
    campaign: "HM Lead Gen — August",
    interest: "Full PMS + Channel Manager",
    budgetLKR: 160000,
    status: "contacted",
    assignedTo: "Ravindu Fernando",
    createdAt: daysAgo(4, 13, 25),
    note: "First call done. Comparing with 2 other vendors.",
  },
  {
    id: "L-1035",
    name: "Shanthi Kumari",
    hotel: "Queens Rest",
    location: "Anuradhapura",
    phone: "+94 78 445 6612",
    source: "walkin",
    campaign: "Walk-in / Referral",
    interest: "PMS Starter",
    status: "lost",
    assignedTo: "Nimmi Perera",
    createdAt: daysAgo(9, 10, 0),
    note: "Budget too low for now. Revisit in high season.",
  },
  {
    id: "L-1034",
    name: "Dilan Weerasinghe",
    hotel: "Palm Breeze Surf Resort",
    location: "Arugam Bay",
    phone: "+94 76 882 4430",
    email: "dilan@palmbreeze.lk",
    source: "instagram",
    campaign: "IG Reels — HotelMate Demo",
    interest: "PMS Pro + Booking Engine",
    budgetLKR: 120000,
    status: "qualified",
    assignedTo: "Ravindu Fernando",
    createdAt: daysAgo(5, 15, 10),
  },
  {
    id: "L-1033",
    name: "Fathima Nizar",
    hotel: "City Comfort Inn",
    location: "Kandy",
    phone: "+94 71 559 8873",
    source: "facebook",
    campaign: "HM Lead Gen — September",
    interest: "Channel Manager only",
    budgetLKR: 55000,
    status: "new",
    assignedTo: "Ashan Silva",
    createdAt: daysAgo(1, 9, 35),
  },
  {
    id: "L-1032",
    name: "Harsha Gunawardena",
    hotel: "Tranquil Lagoon Resort",
    location: "Bentota",
    phone: "+94 77 240 6691",
    email: "harsha@tranquillagoon.lk",
    source: "website",
    campaign: "hotelmate.co.uk — Get Started form",
    interest: "Full PMS + POS + Channel Manager",
    budgetLKR: 230000,
    status: "proposal",
    assignedTo: "Ashan Silva",
    createdAt: daysAgo(7, 12, 45),
    note: "Negotiating annual discount.",
  },
  {
    id: "L-1031",
    name: "Naduni Karunaratne",
    hotel: "Misty Meadows Homestay",
    location: "Ella",
    phone: "+94 70 118 2245",
    source: "facebook",
    campaign: "HM Lead Gen — August",
    interest: "PMS Starter",
    budgetLKR: 35000,
    status: "contacted",
    assignedTo: "Nimmi Perera",
    createdAt: daysAgo(8, 17, 30),
  },
];

export const deals: Deal[] = [
  {
    id: "D-204",
    leadId: "L-1042",
    client: "Nuwan Jayasuriya",
    hotel: "Serendipity Beach Resort",
    plan: "PMS Pro + Channel Manager",
    valueLKR: 185000,
    stage: "inquiry",
    expectedClose: daysAhead(21),
    owner: "Ashan Silva",
  },
  {
    id: "D-203",
    leadId: "L-1040",
    client: "Kasun Bandara",
    hotel: "Hilltop Eco Retreat",
    plan: "PMS Pro + POS",
    valueLKR: 140000,
    stage: "negotiation",
    expectedClose: daysAhead(10),
    owner: "Ashan Silva",
  },
  {
    id: "D-202",
    leadId: "L-1039",
    client: "Tharushi Wickramasinghe",
    hotel: "Sunset Bay Villas",
    plan: "Channel Manager",
    valueLKR: 75000,
    stage: "negotiation",
    expectedClose: daysAhead(5),
    owner: "Ravindu Fernando",
  },
  {
    id: "D-201",
    leadId: "L-1032",
    client: "Harsha Gunawardena",
    hotel: "Tranquil Lagoon Resort",
    plan: "PMS Pro + POS + Channel Manager",
    valueLKR: 230000,
    stage: "negotiation",
    expectedClose: daysAhead(8),
    owner: "Ashan Silva",
  },
  {
    id: "D-200",
    leadId: "L-1041",
    client: "Dilini Fernando",
    hotel: "Cinnamon Grove Boutique",
    plan: "Direct Booking Engine",
    valueLKR: 95000,
    stage: "contacted",
    expectedClose: daysAhead(14),
    owner: "Nimmi Perera",
  },
  {
    id: "D-199",
    leadId: "L-1034",
    client: "Dilan Weerasinghe",
    hotel: "Palm Breeze Surf Resort",
    plan: "PMS Pro + Booking Engine",
    valueLKR: 120000,
    stage: "contacted",
    expectedClose: daysAhead(18),
    owner: "Ravindu Fernando",
  },
  {
    id: "D-198",
    leadId: "L-1036",
    client: "Ruwan Silva",
    hotel: "Blue Horizon Beach Hotel",
    plan: "PMS Pro + Channel Manager",
    valueLKR: 160000,
    stage: "contacted",
    expectedClose: daysAhead(25),
    owner: "Ravindu Fernando",
  },
  {
    id: "D-197",
    leadId: "L-1038",
    client: "Mohamed Rizwan",
    hotel: "Grand Palm Hotel",
    plan: "Enterprise PMS (3 properties)",
    valueLKR: 420000,
    stage: "won",
    expectedClose: daysAgo(1),
    owner: "Ashan Silva",
  },
  {
    id: "D-196",
    leadId: "L-1035",
    client: "Shanthi Kumari",
    hotel: "Queens Rest",
    plan: "PMS Starter",
    valueLKR: 45000,
    stage: "lost",
    owner: "Nimmi Perera",
  },
];

export const followUps: FollowUp[] = [
  {
    id: "F-501",
    leadId: "L-1042",
    leadName: "Nuwan Jayasuriya — Serendipity Beach Resort",
    dueAt: daysAhead(0, 9, 30),
    type: "call",
    note: "First call: intro + schedule demo",
    owner: "Ashan Silva",
    done: false,
  },
  {
    id: "F-502",
    leadId: "L-1037",
    leadName: "Anusha Perera — Lotus Garden Hotel",
    dueAt: daysAhead(0, 11, 0),
    type: "call",
    note: "New FB lead — call within 24h",
    owner: "Nimmi Perera",
    done: false,
  },
  {
    id: "F-503",
    leadId: "L-1039",
    leadName: "Tharushi Wickramasinghe — Sunset Bay Villas",
    dueAt: daysAhead(0, 14, 30),
    type: "whatsapp",
    note: "Follow up on proposal v2",
    owner: "Ravindu Fernando",
    done: false,
  },
  {
    id: "F-504",
    leadId: "L-1033",
    leadName: "Fathima Nizar — City Comfort Inn",
    dueAt: daysAhead(0, 16, 0),
    type: "email",
    note: "Send Channel Manager one-pager",
    owner: "Ashan Silva",
    done: false,
  },
  {
    id: "F-505",
    leadId: "L-1036",
    leadName: "Ruwan Silva — Blue Horizon Beach Hotel",
    dueAt: daysAgo(1, 15, 0),
    type: "call",
    note: "Compare-vendor objection handling",
    owner: "Ravindu Fernando",
    done: false,
  },
  {
    id: "F-506",
    leadId: "L-1040",
    leadName: "Kasun Bandara — Hilltop Eco Retreat",
    dueAt: daysAhead(1, 10, 0),
    type: "meeting",
    note: "Live system demo (Google Meet)",
    owner: "Ashan Silva",
    done: false,
  },
  {
    id: "F-507",
    leadId: "L-1041",
    leadName: "Dilini Fernando — Cinnamon Grove Boutique",
    dueAt: daysAhead(1, 13, 0),
    type: "whatsapp",
    note: "Share pricing sheet + case study",
    owner: "Nimmi Perera",
    done: false,
  },
  {
    id: "F-508",
    leadId: "L-1032",
    leadName: "Harsha Gunawardena — Tranquil Lagoon Resort",
    dueAt: daysAhead(2, 11, 30),
    type: "call",
    note: "Discuss annual discount terms",
    owner: "Ashan Silva",
    done: false,
  },
  {
    id: "F-509",
    leadId: "L-1034",
    leadName: "Dilan Weerasinghe — Palm Breeze Surf Resort",
    dueAt: daysAhead(3, 9, 0),
    type: "meeting",
    note: "On-site visit — Arugam Bay",
    owner: "Ravindu Fernando",
    done: false,
  },
  {
    id: "F-510",
    leadId: "L-1038",
    leadName: "Mohamed Rizwan — Grand Palm Hotel",
    dueAt: daysAhead(4, 10, 0),
    type: "meeting",
    note: "Kick-off onboarding call",
    owner: "Ashan Silva",
    done: false,
  },
];

/* ---------------- helpers ---------------- */

export function getLeadById(id: string): Lead | undefined {
  return leads.find((l) => l.id === id);
}

export const sourceLabels: Record<LeadSource, string> = {
  facebook: "Facebook Lead Form",
  instagram: "Instagram",
  whatsapp: "WhatsApp",
  website: "Website",
  walkin: "Walk-in / Referral",
  manual: "Manual Entry",
};

export const followUpLabels: Record<FollowUpType, string> = {
  call: "Phone call",
  whatsapp: "WhatsApp",
  email: "Email",
  meeting: "Meeting / Demo",
  sms: "SMS",
};
